// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: AccountSettings.proto

package AccountSettings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasicInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBasicInfoRequest) Reset() {
	*x = GetBasicInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicInfoRequest) ProtoMessage() {}

func (x *GetBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{0}
}

type GetBasicInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *BasicInfoModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *GetBasicInfoReply) Reset() {
	*x = GetBasicInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicInfoReply) ProtoMessage() {}

func (x *GetBasicInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicInfoReply.ProtoReflect.Descriptor instead.
func (*GetBasicInfoReply) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasicInfoReply) GetModel() *BasicInfoModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type UpdateBasicInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *BasicInfoModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *UpdateBasicInfoRequest) Reset() {
	*x = UpdateBasicInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasicInfoRequest) ProtoMessage() {}

func (x *UpdateBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBasicInfoRequest) GetModel() *BasicInfoModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type UpdateBasicInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBasicInfoReply) Reset() {
	*x = UpdateBasicInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBasicInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasicInfoReply) ProtoMessage() {}

func (x *UpdateBasicInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasicInfoReply.ProtoReflect.Descriptor instead.
func (*UpdateBasicInfoReply) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{3}
}

type BasicInfoModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName   string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CompanyName string `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	GuiNumber   string `protobuf:"bytes,4,opt,name=gui_number,json=guiNumber,proto3" json:"gui_number,omitempty"`
}

func (x *BasicInfoModel) Reset() {
	*x = BasicInfoModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicInfoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfoModel) ProtoMessage() {}

func (x *BasicInfoModel) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfoModel.ProtoReflect.Descriptor instead.
func (*BasicInfoModel) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{4}
}

func (x *BasicInfoModel) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BasicInfoModel) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *BasicInfoModel) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *BasicInfoModel) GetGuiNumber() string {
	if x != nil {
		return x.GuiNumber
	}
	return ""
}

type GetLoginInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLoginInfoRequest) Reset() {
	*x = GetLoginInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginInfoRequest) ProtoMessage() {}

func (x *GetLoginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLoginInfoRequest) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{5}
}

type GetLoginInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *LoginInfoModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *GetLoginInfoReply) Reset() {
	*x = GetLoginInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginInfoReply) ProtoMessage() {}

func (x *GetLoginInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginInfoReply.ProtoReflect.Descriptor instead.
func (*GetLoginInfoReply) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{6}
}

func (x *GetLoginInfoReply) GetModel() *LoginInfoModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type UpdateLoginInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *LoginInfoModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *UpdateLoginInfoRequest) Reset() {
	*x = UpdateLoginInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLoginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoginInfoRequest) ProtoMessage() {}

func (x *UpdateLoginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoginInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoginInfoRequest) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLoginInfoRequest) GetModel() *LoginInfoModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type UpdateLoginInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLoginInfoReply) Reset() {
	*x = UpdateLoginInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLoginInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoginInfoReply) ProtoMessage() {}

func (x *UpdateLoginInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoginInfoReply.ProtoReflect.Descriptor instead.
func (*UpdateLoginInfoReply) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{8}
}

type LoginInfoModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	EmailAddres string `protobuf:"bytes,2,opt,name=email_addres,json=emailAddres,proto3" json:"email_addres,omitempty"` // get
}

func (x *LoginInfoModel) Reset() {
	*x = LoginInfoModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AccountSettings_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginInfoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInfoModel) ProtoMessage() {}

func (x *LoginInfoModel) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSettings_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInfoModel.ProtoReflect.Descriptor instead.
func (*LoginInfoModel) Descriptor() ([]byte, []int) {
	return file_AccountSettings_proto_rawDescGZIP(), []int{9}
}

func (x *LoginInfoModel) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *LoginInfoModel) GetEmailAddres() string {
	if x != nil {
		return x.EmailAddres
	}
	return ""
}

var File_AccountSettings_proto protoreflect.FileDescriptor

var file_AccountSettings_proto_rawDesc = []byte{
	0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x4f, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x16, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x75, 0x69, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x75, 0x69, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x35, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x4f, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x56, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x4d, 0x45, 0x54,
	0x41, 0x52, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AccountSettings_proto_rawDescOnce sync.Once
	file_AccountSettings_proto_rawDescData = file_AccountSettings_proto_rawDesc
)

func file_AccountSettings_proto_rawDescGZIP() []byte {
	file_AccountSettings_proto_rawDescOnce.Do(func() {
		file_AccountSettings_proto_rawDescData = protoimpl.X.CompressGZIP(file_AccountSettings_proto_rawDescData)
	})
	return file_AccountSettings_proto_rawDescData
}

var file_AccountSettings_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_AccountSettings_proto_goTypes = []interface{}{
	(*GetBasicInfoRequest)(nil),    // 0: AccountSettings.GetBasicInfoRequest
	(*GetBasicInfoReply)(nil),      // 1: AccountSettings.GetBasicInfoReply
	(*UpdateBasicInfoRequest)(nil), // 2: AccountSettings.UpdateBasicInfoRequest
	(*UpdateBasicInfoReply)(nil),   // 3: AccountSettings.UpdateBasicInfoReply
	(*BasicInfoModel)(nil),         // 4: AccountSettings.BasicInfoModel
	(*GetLoginInfoRequest)(nil),    // 5: AccountSettings.GetLoginInfoRequest
	(*GetLoginInfoReply)(nil),      // 6: AccountSettings.GetLoginInfoReply
	(*UpdateLoginInfoRequest)(nil), // 7: AccountSettings.UpdateLoginInfoRequest
	(*UpdateLoginInfoReply)(nil),   // 8: AccountSettings.UpdateLoginInfoReply
	(*LoginInfoModel)(nil),         // 9: AccountSettings.LoginInfoModel
}
var file_AccountSettings_proto_depIdxs = []int32{
	4, // 0: AccountSettings.GetBasicInfoReply.model:type_name -> AccountSettings.BasicInfoModel
	4, // 1: AccountSettings.UpdateBasicInfoRequest.model:type_name -> AccountSettings.BasicInfoModel
	9, // 2: AccountSettings.GetLoginInfoReply.model:type_name -> AccountSettings.LoginInfoModel
	9, // 3: AccountSettings.UpdateLoginInfoRequest.model:type_name -> AccountSettings.LoginInfoModel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_AccountSettings_proto_init() }
func file_AccountSettings_proto_init() {
	if File_AccountSettings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AccountSettings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBasicInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBasicInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicInfoModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLoginInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLoginInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AccountSettings_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginInfoModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AccountSettings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountSettings_proto_goTypes,
		DependencyIndexes: file_AccountSettings_proto_depIdxs,
		MessageInfos:      file_AccountSettings_proto_msgTypes,
	}.Build()
	File_AccountSettings_proto = out.File
	file_AccountSettings_proto_rawDesc = nil
	file_AccountSettings_proto_goTypes = nil
	file_AccountSettings_proto_depIdxs = nil
}
