// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: ThirdPartyArContent.proto

package ThirdPartyArContent

import (
	ThirdPartyCommon "service/protos/ThirdPartyCommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArContentTemplateType int32

const (
	ArContentTemplateType_TEMPLATE_GLASSES ArContentTemplateType = 0
	ArContentTemplateType_TEMPLATE_EARRING ArContentTemplateType = 1
)

// Enum value maps for ArContentTemplateType.
var (
	ArContentTemplateType_name = map[int32]string{
		0: "TEMPLATE_GLASSES",
		1: "TEMPLATE_EARRING",
	}
	ArContentTemplateType_value = map[string]int32{
		"TEMPLATE_GLASSES": 0,
		"TEMPLATE_EARRING": 1,
	}
)

func (x ArContentTemplateType) Enum() *ArContentTemplateType {
	p := new(ArContentTemplateType)
	*p = x
	return p
}

func (x ArContentTemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArContentTemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_ThirdPartyArContent_proto_enumTypes[0].Descriptor()
}

func (ArContentTemplateType) Type() protoreflect.EnumType {
	return &file_ThirdPartyArContent_proto_enumTypes[0]
}

func (x ArContentTemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArContentTemplateType.Descriptor instead.
func (ArContentTemplateType) EnumDescriptor() ([]byte, []int) {
	return file_ThirdPartyArContent_proto_rawDescGZIP(), []int{0}
}

type CreateArContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TemplateType ArContentTemplateType `protobuf:"varint,2,opt,name=template_type,json=templateType,proto3,enum=ThirdPartyArContent.ArContentTemplateType" json:"template_type,omitempty"`
}

func (x *CreateArContentRequest) Reset() {
	*x = CreateArContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdPartyArContent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArContentRequest) ProtoMessage() {}

func (x *CreateArContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdPartyArContent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArContentRequest.ProtoReflect.Descriptor instead.
func (*CreateArContentRequest) Descriptor() ([]byte, []int) {
	return file_ThirdPartyArContent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateArContentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateArContentRequest) GetTemplateType() ArContentTemplateType {
	if x != nil {
		return x.TemplateType
	}
	return ArContentTemplateType_TEMPLATE_GLASSES
}

type CreateArContentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArContentId string                      `protobuf:"bytes,1,opt,name=ar_content_id,json=arContentId,proto3" json:"ar_content_id,omitempty"`
	State       ThirdPartyCommon.StatusCode `protobuf:"varint,2,opt,name=state,proto3,enum=ThirdPartyCommon.StatusCode" json:"state,omitempty"`
}

func (x *CreateArContentReply) Reset() {
	*x = CreateArContentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdPartyArContent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArContentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArContentReply) ProtoMessage() {}

func (x *CreateArContentReply) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdPartyArContent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArContentReply.ProtoReflect.Descriptor instead.
func (*CreateArContentReply) Descriptor() ([]byte, []int) {
	return file_ThirdPartyArContent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArContentReply) GetArContentId() string {
	if x != nil {
		return x.ArContentId
	}
	return ""
}

func (x *CreateArContentReply) GetState() ThirdPartyCommon.StatusCode {
	if x != nil {
		return x.State
	}
	return ThirdPartyCommon.StatusCode(0)
}

type GetArLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArContentId string `protobuf:"bytes,1,opt,name=ar_content_id,json=arContentId,proto3" json:"ar_content_id,omitempty"`
}

func (x *GetArLinkRequest) Reset() {
	*x = GetArLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdPartyArContent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArLinkRequest) ProtoMessage() {}

func (x *GetArLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdPartyArContent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArLinkRequest.ProtoReflect.Descriptor instead.
func (*GetArLinkRequest) Descriptor() ([]byte, []int) {
	return file_ThirdPartyArContent_proto_rawDescGZIP(), []int{2}
}

func (x *GetArLinkRequest) GetArContentId() string {
	if x != nil {
		return x.ArContentId
	}
	return ""
}

type GetArLinkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArContentViewerPath string                      `protobuf:"bytes,1,opt,name=ar_content_viewer_path,json=arContentViewerPath,proto3" json:"ar_content_viewer_path,omitempty"`
	State               ThirdPartyCommon.StatusCode `protobuf:"varint,2,opt,name=state,proto3,enum=ThirdPartyCommon.StatusCode" json:"state,omitempty"`
}

func (x *GetArLinkReply) Reset() {
	*x = GetArLinkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ThirdPartyArContent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArLinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArLinkReply) ProtoMessage() {}

func (x *GetArLinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_ThirdPartyArContent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArLinkReply.ProtoReflect.Descriptor instead.
func (*GetArLinkReply) Descriptor() ([]byte, []int) {
	return file_ThirdPartyArContent_proto_rawDescGZIP(), []int{3}
}

func (x *GetArLinkReply) GetArContentViewerPath() string {
	if x != nil {
		return x.ArContentViewerPath
	}
	return ""
}

func (x *GetArLinkReply) GetState() ThirdPartyCommon.StatusCode {
	if x != nil {
		return x.State
	}
	return ThirdPartyCommon.StatusCode(0)
}

var File_ThirdPartyArContent_proto protoreflect.FileDescriptor

var file_ThirdPartyArContent_proto_rawDesc = []byte{
	0x0a, 0x19, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41, 0x72, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x54, 0x68, 0x69,
	0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x1a, 0x16, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6e, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x22, 0x0a, 0x0d, 0x61, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x61,
	0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x79, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x33, 0x0a, 0x16, 0x61, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f,
	0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x13, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77,
	0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x43, 0x0a, 0x15, 0x41, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f,
	0x47, 0x4c, 0x41, 0x53, 0x53, 0x45, 0x53, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x45, 0x4d,
	0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x41, 0x52, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x42,
	0x2a, 0x5a, 0x28, 0x4d, 0x45, 0x54, 0x41, 0x52, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ThirdPartyArContent_proto_rawDescOnce sync.Once
	file_ThirdPartyArContent_proto_rawDescData = file_ThirdPartyArContent_proto_rawDesc
)

func file_ThirdPartyArContent_proto_rawDescGZIP() []byte {
	file_ThirdPartyArContent_proto_rawDescOnce.Do(func() {
		file_ThirdPartyArContent_proto_rawDescData = protoimpl.X.CompressGZIP(file_ThirdPartyArContent_proto_rawDescData)
	})
	return file_ThirdPartyArContent_proto_rawDescData
}

var file_ThirdPartyArContent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ThirdPartyArContent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ThirdPartyArContent_proto_goTypes = []interface{}{
	(ArContentTemplateType)(0),       // 0: ThirdPartyArContent.ArContentTemplateType
	(*CreateArContentRequest)(nil),   // 1: ThirdPartyArContent.CreateArContentRequest
	(*CreateArContentReply)(nil),     // 2: ThirdPartyArContent.CreateArContentReply
	(*GetArLinkRequest)(nil),         // 3: ThirdPartyArContent.GetArLinkRequest
	(*GetArLinkReply)(nil),           // 4: ThirdPartyArContent.GetArLinkReply
	(ThirdPartyCommon.StatusCode)(0), // 5: ThirdPartyCommon.StatusCode
}
var file_ThirdPartyArContent_proto_depIdxs = []int32{
	0, // 0: ThirdPartyArContent.CreateArContentRequest.template_type:type_name -> ThirdPartyArContent.ArContentTemplateType
	5, // 1: ThirdPartyArContent.CreateArContentReply.state:type_name -> ThirdPartyCommon.StatusCode
	5, // 2: ThirdPartyArContent.GetArLinkReply.state:type_name -> ThirdPartyCommon.StatusCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ThirdPartyArContent_proto_init() }
func file_ThirdPartyArContent_proto_init() {
	if File_ThirdPartyArContent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ThirdPartyArContent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdPartyArContent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArContentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdPartyArContent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ThirdPartyArContent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArLinkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ThirdPartyArContent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ThirdPartyArContent_proto_goTypes,
		DependencyIndexes: file_ThirdPartyArContent_proto_depIdxs,
		EnumInfos:         file_ThirdPartyArContent_proto_enumTypes,
		MessageInfos:      file_ThirdPartyArContent_proto_msgTypes,
	}.Build()
	File_ThirdPartyArContent_proto = out.File
	file_ThirdPartyArContent_proto_rawDesc = nil
	file_ThirdPartyArContent_proto_goTypes = nil
	file_ThirdPartyArContent_proto_depIdxs = nil
}
