// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: ThirdPartyCommon.proto

package ThirdPartyCommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_StatusCode_NONE StatusCode = 0
	// Auth
	StatusCode_SUCCESS       StatusCode = 10000
	StatusCode_AUTH_ERROR    StatusCode = 10002
	StatusCode_INVAILD_TOKEN StatusCode = 10001
	// API
	StatusCode_INVAILD_PARAM_ERROR StatusCode = 20001
	StatusCode_INTERNAL_ERROR      StatusCode = 20002
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:     "StatusCode_NONE",
		10000: "SUCCESS",
		10002: "AUTH_ERROR",
		10001: "INVAILD_TOKEN",
		20001: "INVAILD_PARAM_ERROR",
		20002: "INTERNAL_ERROR",
	}
	StatusCode_value = map[string]int32{
		"StatusCode_NONE":     0,
		"SUCCESS":             10000,
		"AUTH_ERROR":          10002,
		"INVAILD_TOKEN":       10001,
		"INVAILD_PARAM_ERROR": 20001,
		"INTERNAL_ERROR":      20002,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ThirdPartyCommon_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_ThirdPartyCommon_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_ThirdPartyCommon_proto_rawDescGZIP(), []int{0}
}

var File_ThirdPartyCommon_proto protoreflect.FileDescriptor

var file_ThirdPartyCommon_proto_rawDesc = []byte{
	0x0a, 0x16, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50,
	0x61, 0x72, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x85, 0x01, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x90, 0x4e, 0x12, 0x0f, 0x0a, 0x0a,
	0x41, 0x55, 0x54, 0x48, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x92, 0x4e, 0x12, 0x12, 0x0a,
	0x0d, 0x49, 0x4e, 0x56, 0x41, 0x49, 0x4c, 0x44, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x91,
	0x4e, 0x12, 0x19, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41, 0x49, 0x4c, 0x44, 0x5f, 0x50, 0x41, 0x52,
	0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xa1, 0x9c, 0x01, 0x12, 0x14, 0x0a, 0x0e,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xa2,
	0x9c, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x4d, 0x45, 0x54, 0x41, 0x52, 0x5f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ThirdPartyCommon_proto_rawDescOnce sync.Once
	file_ThirdPartyCommon_proto_rawDescData = file_ThirdPartyCommon_proto_rawDesc
)

func file_ThirdPartyCommon_proto_rawDescGZIP() []byte {
	file_ThirdPartyCommon_proto_rawDescOnce.Do(func() {
		file_ThirdPartyCommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_ThirdPartyCommon_proto_rawDescData)
	})
	return file_ThirdPartyCommon_proto_rawDescData
}

var file_ThirdPartyCommon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ThirdPartyCommon_proto_goTypes = []interface{}{
	(StatusCode)(0), // 0: ThirdPartyCommon.StatusCode
}
var file_ThirdPartyCommon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ThirdPartyCommon_proto_init() }
func file_ThirdPartyCommon_proto_init() {
	if File_ThirdPartyCommon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ThirdPartyCommon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ThirdPartyCommon_proto_goTypes,
		DependencyIndexes: file_ThirdPartyCommon_proto_depIdxs,
		EnumInfos:         file_ThirdPartyCommon_proto_enumTypes,
	}.Build()
	File_ThirdPartyCommon_proto = out.File
	file_ThirdPartyCommon_proto_rawDesc = nil
	file_ThirdPartyCommon_proto_goTypes = nil
	file_ThirdPartyCommon_proto_depIdxs = nil
}
