// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: Permission.proto

package Permission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServicesName     string             `protobuf:"bytes,2,opt,name=services_name,json=servicesName,proto3" json:"services_name,omitempty"`
	PermissionModels []*PermissionModel `protobuf:"bytes,3,rep,name=permission_models,json=permissionModels,proto3" json:"permission_models,omitempty"`
}

func (x *PermissionPackage) Reset() {
	*x = PermissionPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Permission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionPackage) ProtoMessage() {}

func (x *PermissionPackage) ProtoReflect() protoreflect.Message {
	mi := &file_Permission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionPackage.ProtoReflect.Descriptor instead.
func (*PermissionPackage) Descriptor() ([]byte, []int) {
	return file_Permission_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionPackage) GetServicesName() string {
	if x != nil {
		return x.ServicesName
	}
	return ""
}

func (x *PermissionPackage) GetPermissionModels() []*PermissionModel {
	if x != nil {
		return x.PermissionModels
	}
	return nil
}

type PermissionModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RpcName string `protobuf:"bytes,3,opt,name=rpc_name,json=rpcName,proto3" json:"rpc_name,omitempty"`
}

func (x *PermissionModel) Reset() {
	*x = PermissionModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Permission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionModel) ProtoMessage() {}

func (x *PermissionModel) ProtoReflect() protoreflect.Message {
	mi := &file_Permission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionModel.ProtoReflect.Descriptor instead.
func (*PermissionModel) Descriptor() ([]byte, []int) {
	return file_Permission_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionModel) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	return ""
}

type GetDefaultPermissionGroupListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDefaultPermissionGroupListRequest) Reset() {
	*x = GetDefaultPermissionGroupListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Permission_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultPermissionGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultPermissionGroupListRequest) ProtoMessage() {}

func (x *GetDefaultPermissionGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Permission_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultPermissionGroupListRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultPermissionGroupListRequest) Descriptor() ([]byte, []int) {
	return file_Permission_proto_rawDescGZIP(), []int{2}
}

type GetDefaultPermissionGroupListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*PermissionGroupModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
}

func (x *GetDefaultPermissionGroupListReply) Reset() {
	*x = GetDefaultPermissionGroupListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Permission_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefaultPermissionGroupListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultPermissionGroupListReply) ProtoMessage() {}

func (x *GetDefaultPermissionGroupListReply) ProtoReflect() protoreflect.Message {
	mi := &file_Permission_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultPermissionGroupListReply.ProtoReflect.Descriptor instead.
func (*GetDefaultPermissionGroupListReply) Descriptor() ([]byte, []int) {
	return file_Permission_proto_rawDescGZIP(), []int{3}
}

func (x *GetDefaultPermissionGroupListReply) GetModels() []*PermissionGroupModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type PermissionGroupModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermissionGroupId    string   `protobuf:"bytes,1,opt,name=permission_group_id,json=permissionGroupId,proto3" json:"permission_group_id,omitempty"` // update
	PermissionGroupName  string   `protobuf:"bytes,2,opt,name=permission_group_name,json=permissionGroupName,proto3" json:"permission_group_name,omitempty"`
	PermissionSeletedIds []string `protobuf:"bytes,3,rep,name=permission_seleted_ids,json=permissionSeletedIds,proto3" json:"permission_seleted_ids,omitempty"`
}

func (x *PermissionGroupModel) Reset() {
	*x = PermissionGroupModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Permission_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionGroupModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGroupModel) ProtoMessage() {}

func (x *PermissionGroupModel) ProtoReflect() protoreflect.Message {
	mi := &file_Permission_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGroupModel.ProtoReflect.Descriptor instead.
func (*PermissionGroupModel) Descriptor() ([]byte, []int) {
	return file_Permission_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionGroupModel) GetPermissionGroupId() string {
	if x != nil {
		return x.PermissionGroupId
	}
	return ""
}

func (x *PermissionGroupModel) GetPermissionGroupName() string {
	if x != nil {
		return x.PermissionGroupName
	}
	return ""
}

func (x *PermissionGroupModel) GetPermissionSeletedIds() []string {
	if x != nil {
		return x.PermissionSeletedIds
	}
	return nil
}

var File_Permission_proto protoreflect.FileDescriptor

var file_Permission_proto_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x96,
	0x01, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a,
	0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x10, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x50, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x24, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x5e, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x22, 0xb0, 0x01, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34,
	0x0a, 0x16, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x49, 0x64, 0x73, 0x42, 0x21, 0x5a, 0x1f, 0x4d, 0x45, 0x54, 0x41, 0x52, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Permission_proto_rawDescOnce sync.Once
	file_Permission_proto_rawDescData = file_Permission_proto_rawDesc
)

func file_Permission_proto_rawDescGZIP() []byte {
	file_Permission_proto_rawDescOnce.Do(func() {
		file_Permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_Permission_proto_rawDescData)
	})
	return file_Permission_proto_rawDescData
}

var file_Permission_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Permission_proto_goTypes = []interface{}{
	(*PermissionPackage)(nil),                    // 0: Permission.PermissionPackage
	(*PermissionModel)(nil),                      // 1: Permission.PermissionModel
	(*GetDefaultPermissionGroupListRequest)(nil), // 2: Permission.GetDefaultPermissionGroupListRequest
	(*GetDefaultPermissionGroupListReply)(nil),   // 3: Permission.GetDefaultPermissionGroupListReply
	(*PermissionGroupModel)(nil),                 // 4: Permission.PermissionGroupModel
}
var file_Permission_proto_depIdxs = []int32{
	1, // 0: Permission.PermissionPackage.permission_models:type_name -> Permission.PermissionModel
	4, // 1: Permission.GetDefaultPermissionGroupListReply.models:type_name -> Permission.PermissionGroupModel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Permission_proto_init() }
func file_Permission_proto_init() {
	if File_Permission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Permission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Permission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Permission_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultPermissionGroupListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Permission_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefaultPermissionGroupListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Permission_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionGroupModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Permission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Permission_proto_goTypes,
		DependencyIndexes: file_Permission_proto_depIdxs,
		MessageInfos:      file_Permission_proto_msgTypes,
	}.Build()
	File_Permission_proto = out.File
	file_Permission_proto_rawDesc = nil
	file_Permission_proto_goTypes = nil
	file_Permission_proto_depIdxs = nil
}
