// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: ErrorCode.proto

package ErrorCode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_ERROR_TYPE_NONE       ErrorType = 0
	ErrorType_ERROR_TYPE_AUTH       ErrorType = 1
	ErrorType_ERROR_TYPE_AR_CONTENT ErrorType = 2
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "ERROR_TYPE_NONE",
		1: "ERROR_TYPE_AUTH",
		2: "ERROR_TYPE_AR_CONTENT",
	}
	ErrorType_value = map[string]int32{
		"ERROR_TYPE_NONE":       0,
		"ERROR_TYPE_AUTH":       1,
		"ERROR_TYPE_AR_CONTENT": 2,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_ErrorCode_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_ErrorCode_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_ErrorCode_proto_rawDescGZIP(), []int{0}
}

type ERROR_AUTH int32

const (
	ERROR_AUTH_ERROR_AUTH_NONE  ERROR_AUTH = 0
	ERROR_AUTH_ERROR_LOGIN_FAIL ERROR_AUTH = 10000
)

// Enum value maps for ERROR_AUTH.
var (
	ERROR_AUTH_name = map[int32]string{
		0:     "ERROR_AUTH_NONE",
		10000: "ERROR_LOGIN_FAIL",
	}
	ERROR_AUTH_value = map[string]int32{
		"ERROR_AUTH_NONE":  0,
		"ERROR_LOGIN_FAIL": 10000,
	}
)

func (x ERROR_AUTH) Enum() *ERROR_AUTH {
	p := new(ERROR_AUTH)
	*p = x
	return p
}

func (x ERROR_AUTH) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERROR_AUTH) Descriptor() protoreflect.EnumDescriptor {
	return file_ErrorCode_proto_enumTypes[1].Descriptor()
}

func (ERROR_AUTH) Type() protoreflect.EnumType {
	return &file_ErrorCode_proto_enumTypes[1]
}

func (x ERROR_AUTH) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERROR_AUTH.Descriptor instead.
func (ERROR_AUTH) EnumDescriptor() ([]byte, []int) {
	return file_ErrorCode_proto_rawDescGZIP(), []int{1}
}

type ERROR_AR_CONTENT int32

const (
	ERROR_AR_CONTENT_ERROR_AR_CONTENT_NONE ERROR_AR_CONTENT = 0
	ERROR_AR_CONTENT_ERROR_AR_CONTENT_FAIL ERROR_AR_CONTENT = 50000
)

// Enum value maps for ERROR_AR_CONTENT.
var (
	ERROR_AR_CONTENT_name = map[int32]string{
		0:     "ERROR_AR_CONTENT_NONE",
		50000: "ERROR_AR_CONTENT_FAIL",
	}
	ERROR_AR_CONTENT_value = map[string]int32{
		"ERROR_AR_CONTENT_NONE": 0,
		"ERROR_AR_CONTENT_FAIL": 50000,
	}
)

func (x ERROR_AR_CONTENT) Enum() *ERROR_AR_CONTENT {
	p := new(ERROR_AR_CONTENT)
	*p = x
	return p
}

func (x ERROR_AR_CONTENT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERROR_AR_CONTENT) Descriptor() protoreflect.EnumDescriptor {
	return file_ErrorCode_proto_enumTypes[2].Descriptor()
}

func (ERROR_AR_CONTENT) Type() protoreflect.EnumType {
	return &file_ErrorCode_proto_enumTypes[2]
}

func (x ERROR_AR_CONTENT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERROR_AR_CONTENT.Descriptor instead.
func (ERROR_AR_CONTENT) EnumDescriptor() ([]byte, []int) {
	return file_ErrorCode_proto_rawDescGZIP(), []int{2}
}

var File_ErrorCode_proto protoreflect.FileDescriptor

var file_ErrorCode_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x50, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x55, 0x54,
	0x48, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x41, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x2a, 0x38,
	0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x10, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x90, 0x4e, 0x2a, 0x4a, 0x0a, 0x10, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x41, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x12, 0x19, 0x0a, 0x15,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x41, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54,
	0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x15, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x41, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x10, 0xd0, 0x86, 0x03, 0x42, 0x20, 0x5a, 0x1e, 0x4d, 0x45, 0x54, 0x41, 0x52, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ErrorCode_proto_rawDescOnce sync.Once
	file_ErrorCode_proto_rawDescData = file_ErrorCode_proto_rawDesc
)

func file_ErrorCode_proto_rawDescGZIP() []byte {
	file_ErrorCode_proto_rawDescOnce.Do(func() {
		file_ErrorCode_proto_rawDescData = protoimpl.X.CompressGZIP(file_ErrorCode_proto_rawDescData)
	})
	return file_ErrorCode_proto_rawDescData
}

var file_ErrorCode_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ErrorCode_proto_goTypes = []interface{}{
	(ErrorType)(0),        // 0: ErrorCode.ErrorType
	(ERROR_AUTH)(0),       // 1: ErrorCode.ERROR_AUTH
	(ERROR_AR_CONTENT)(0), // 2: ErrorCode.ERROR_AR_CONTENT
}
var file_ErrorCode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ErrorCode_proto_init() }
func file_ErrorCode_proto_init() {
	if File_ErrorCode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ErrorCode_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ErrorCode_proto_goTypes,
		DependencyIndexes: file_ErrorCode_proto_depIdxs,
		EnumInfos:         file_ErrorCode_proto_enumTypes,
	}.Build()
	File_ErrorCode_proto = out.File
	file_ErrorCode_proto_rawDesc = nil
	file_ErrorCode_proto_goTypes = nil
	file_ErrorCode_proto_depIdxs = nil
}
