// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: Statistic.proto

package Statistic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticType int32

const (
	StatisticType_STATISTIC_TYPE_NONE       StatisticType = 0
	StatisticType_VIEWER_OPEN               StatisticType = 1
	StatisticType_VIEWER_INITED             StatisticType = 2
	StatisticType_VIEWER_TAKE_PICTURE       StatisticType = 3
	StatisticType_CLICK_VIEWER_RIGHT_BUTTEN StatisticType = 4
	StatisticType_CLICK_VIEWER_LEFT_BUTTEN  StatisticType = 5
)

// Enum value maps for StatisticType.
var (
	StatisticType_name = map[int32]string{
		0: "STATISTIC_TYPE_NONE",
		1: "VIEWER_OPEN",
		2: "VIEWER_INITED",
		3: "VIEWER_TAKE_PICTURE",
		4: "CLICK_VIEWER_RIGHT_BUTTEN",
		5: "CLICK_VIEWER_LEFT_BUTTEN",
	}
	StatisticType_value = map[string]int32{
		"STATISTIC_TYPE_NONE":       0,
		"VIEWER_OPEN":               1,
		"VIEWER_INITED":             2,
		"VIEWER_TAKE_PICTURE":       3,
		"CLICK_VIEWER_RIGHT_BUTTEN": 4,
		"CLICK_VIEWER_LEFT_BUTTEN":  5,
	}
)

func (x StatisticType) Enum() *StatisticType {
	p := new(StatisticType)
	*p = x
	return p
}

func (x StatisticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatisticType) Descriptor() protoreflect.EnumDescriptor {
	return file_Statistic_proto_enumTypes[0].Descriptor()
}

func (StatisticType) Type() protoreflect.EnumType {
	return &file_Statistic_proto_enumTypes[0]
}

func (x StatisticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatisticType.Descriptor instead.
func (StatisticType) EnumDescriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{0}
}

type AddCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArContentId string        `protobuf:"bytes,1,opt,name=ar_content_id,json=arContentId,proto3" json:"ar_content_id,omitempty"`
	AdminId     string        `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Type        StatisticType `protobuf:"varint,3,opt,name=type,proto3,enum=Statistic.StatisticType" json:"type,omitempty"`
}

func (x *AddCountRequest) Reset() {
	*x = AddCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCountRequest) ProtoMessage() {}

func (x *AddCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCountRequest.ProtoReflect.Descriptor instead.
func (*AddCountRequest) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{0}
}

func (x *AddCountRequest) GetArContentId() string {
	if x != nil {
		return x.ArContentId
	}
	return ""
}

func (x *AddCountRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *AddCountRequest) GetType() StatisticType {
	if x != nil {
		return x.Type
	}
	return StatisticType_STATISTIC_TYPE_NONE
}

type GetArContentDayInfoSumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatetimeStart string        `protobuf:"bytes,1,opt,name=datetime_start,json=datetimeStart,proto3" json:"datetime_start,omitempty"`
	DatetimeEnd   string        `protobuf:"bytes,2,opt,name=datetime_end,json=datetimeEnd,proto3" json:"datetime_end,omitempty"`
	Type          StatisticType `protobuf:"varint,3,opt,name=type,proto3,enum=Statistic.StatisticType" json:"type,omitempty"`
}

func (x *GetArContentDayInfoSumRequest) Reset() {
	*x = GetArContentDayInfoSumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArContentDayInfoSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArContentDayInfoSumRequest) ProtoMessage() {}

func (x *GetArContentDayInfoSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArContentDayInfoSumRequest.ProtoReflect.Descriptor instead.
func (*GetArContentDayInfoSumRequest) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{1}
}

func (x *GetArContentDayInfoSumRequest) GetDatetimeStart() string {
	if x != nil {
		return x.DatetimeStart
	}
	return ""
}

func (x *GetArContentDayInfoSumRequest) GetDatetimeEnd() string {
	if x != nil {
		return x.DatetimeEnd
	}
	return ""
}

func (x *GetArContentDayInfoSumRequest) GetType() StatisticType {
	if x != nil {
		return x.Type
	}
	return StatisticType_STATISTIC_TYPE_NONE
}

type GetArContentDayInfoSumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DayInfoModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetArContentDayInfoSumReply) Reset() {
	*x = GetArContentDayInfoSumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArContentDayInfoSumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArContentDayInfoSumReply) ProtoMessage() {}

func (x *GetArContentDayInfoSumReply) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArContentDayInfoSumReply.ProtoReflect.Descriptor instead.
func (*GetArContentDayInfoSumReply) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{2}
}

func (x *GetArContentDayInfoSumReply) GetData() []*DayInfoModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetArContentDropDownListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetArContentDropDownListRequest) Reset() {
	*x = GetArContentDropDownListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArContentDropDownListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArContentDropDownListRequest) ProtoMessage() {}

func (x *GetArContentDropDownListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArContentDropDownListRequest.ProtoReflect.Descriptor instead.
func (*GetArContentDropDownListRequest) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{3}
}

type GetArContentDropDownListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ArContentDropDownList `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetArContentDropDownListReply) Reset() {
	*x = GetArContentDropDownListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArContentDropDownListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArContentDropDownListReply) ProtoMessage() {}

func (x *GetArContentDropDownListReply) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArContentDropDownListReply.ProtoReflect.Descriptor instead.
func (*GetArContentDropDownListReply) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{4}
}

func (x *GetArContentDropDownListReply) GetData() []*ArContentDropDownList {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetArContentDayInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatetimeStart string        `protobuf:"bytes,1,opt,name=datetime_start,json=datetimeStart,proto3" json:"datetime_start,omitempty"`
	DatetimeEnd   string        `protobuf:"bytes,2,opt,name=datetime_end,json=datetimeEnd,proto3" json:"datetime_end,omitempty"`
	Type          StatisticType `protobuf:"varint,3,opt,name=type,proto3,enum=Statistic.StatisticType" json:"type,omitempty"`
	ArContentId   string        `protobuf:"bytes,4,opt,name=ar_content_id,json=arContentId,proto3" json:"ar_content_id,omitempty"`
}

func (x *GetArContentDayInfoRequest) Reset() {
	*x = GetArContentDayInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArContentDayInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArContentDayInfoRequest) ProtoMessage() {}

func (x *GetArContentDayInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArContentDayInfoRequest.ProtoReflect.Descriptor instead.
func (*GetArContentDayInfoRequest) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{5}
}

func (x *GetArContentDayInfoRequest) GetDatetimeStart() string {
	if x != nil {
		return x.DatetimeStart
	}
	return ""
}

func (x *GetArContentDayInfoRequest) GetDatetimeEnd() string {
	if x != nil {
		return x.DatetimeEnd
	}
	return ""
}

func (x *GetArContentDayInfoRequest) GetType() StatisticType {
	if x != nil {
		return x.Type
	}
	return StatisticType_STATISTIC_TYPE_NONE
}

func (x *GetArContentDayInfoRequest) GetArContentId() string {
	if x != nil {
		return x.ArContentId
	}
	return ""
}

type GetArContentDayInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DayInfoModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetArContentDayInfoReply) Reset() {
	*x = GetArContentDayInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArContentDayInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArContentDayInfoReply) ProtoMessage() {}

func (x *GetArContentDayInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArContentDayInfoReply.ProtoReflect.Descriptor instead.
func (*GetArContentDayInfoReply) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{6}
}

func (x *GetArContentDayInfoReply) GetData() []*DayInfoModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArContentDropDownList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArContentId string `protobuf:"bytes,1,opt,name=ar_content_id,json=arContentId,proto3" json:"ar_content_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ArContentDropDownList) Reset() {
	*x = ArContentDropDownList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArContentDropDownList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArContentDropDownList) ProtoMessage() {}

func (x *ArContentDropDownList) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArContentDropDownList.ProtoReflect.Descriptor instead.
func (*ArContentDropDownList) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{7}
}

func (x *ArContentDropDownList) GetArContentId() string {
	if x != nil {
		return x.ArContentId
	}
	return ""
}

func (x *ArContentDropDownList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DayInfoModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datetime string `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Count    int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DayInfoModel) Reset() {
	*x = DayInfoModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Statistic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayInfoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayInfoModel) ProtoMessage() {}

func (x *DayInfoModel) ProtoReflect() protoreflect.Message {
	mi := &file_Statistic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayInfoModel.ProtoReflect.Descriptor instead.
func (*DayInfoModel) Descriptor() ([]byte, []int) {
	return file_Statistic_proto_rawDescGZIP(), []int{8}
}

func (x *DayInfoModel) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *DayInfoModel) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_Statistic_proto protoreflect.FileDescriptor

var file_Statistic_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x22, 0x7e, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0d, 0x61, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x97, 0x01, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4a, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x72, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x75, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e,
	0x44, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x21, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x72, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x2e, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f,
	0x77, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb8, 0x01, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x65,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x44, 0x61,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x4f, 0x0a, 0x15, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x6f,
	0x70, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x72, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x40, 0x0a, 0x0c, 0x44, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2a, 0xa2, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x49, 0x53, 0x54,
	0x49, 0x43, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x54, 0x41, 0x4b,
	0x45, 0x5f, 0x50, 0x49, 0x43, 0x54, 0x55, 0x52, 0x45, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x43,
	0x4c, 0x49, 0x43, 0x4b, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x5f, 0x42, 0x55, 0x54, 0x54, 0x45, 0x4e, 0x10, 0x04, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4c,
	0x49, 0x43, 0x4b, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x5f,
	0x42, 0x55, 0x54, 0x54, 0x45, 0x4e, 0x10, 0x05, 0x42, 0x20, 0x5a, 0x1e, 0x4d, 0x45, 0x54, 0x41,
	0x52, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_Statistic_proto_rawDescOnce sync.Once
	file_Statistic_proto_rawDescData = file_Statistic_proto_rawDesc
)

func file_Statistic_proto_rawDescGZIP() []byte {
	file_Statistic_proto_rawDescOnce.Do(func() {
		file_Statistic_proto_rawDescData = protoimpl.X.CompressGZIP(file_Statistic_proto_rawDescData)
	})
	return file_Statistic_proto_rawDescData
}

var file_Statistic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Statistic_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Statistic_proto_goTypes = []interface{}{
	(StatisticType)(0),                      // 0: Statistic.StatisticType
	(*AddCountRequest)(nil),                 // 1: Statistic.AddCountRequest
	(*GetArContentDayInfoSumRequest)(nil),   // 2: Statistic.GetArContentDayInfoSumRequest
	(*GetArContentDayInfoSumReply)(nil),     // 3: Statistic.GetArContentDayInfoSumReply
	(*GetArContentDropDownListRequest)(nil), // 4: Statistic.GetArContentDropDownListRequest
	(*GetArContentDropDownListReply)(nil),   // 5: Statistic.GetArContentDropDownListReply
	(*GetArContentDayInfoRequest)(nil),      // 6: Statistic.GetArContentDayInfoRequest
	(*GetArContentDayInfoReply)(nil),        // 7: Statistic.GetArContentDayInfoReply
	(*ArContentDropDownList)(nil),           // 8: Statistic.ArContentDropDownList
	(*DayInfoModel)(nil),                    // 9: Statistic.DayInfoModel
}
var file_Statistic_proto_depIdxs = []int32{
	0, // 0: Statistic.AddCountRequest.type:type_name -> Statistic.StatisticType
	0, // 1: Statistic.GetArContentDayInfoSumRequest.type:type_name -> Statistic.StatisticType
	9, // 2: Statistic.GetArContentDayInfoSumReply.data:type_name -> Statistic.DayInfoModel
	8, // 3: Statistic.GetArContentDropDownListReply.data:type_name -> Statistic.ArContentDropDownList
	0, // 4: Statistic.GetArContentDayInfoRequest.type:type_name -> Statistic.StatisticType
	9, // 5: Statistic.GetArContentDayInfoReply.data:type_name -> Statistic.DayInfoModel
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Statistic_proto_init() }
func file_Statistic_proto_init() {
	if File_Statistic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Statistic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArContentDayInfoSumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArContentDayInfoSumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArContentDropDownListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArContentDropDownListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArContentDayInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArContentDayInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArContentDropDownList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Statistic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayInfoModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Statistic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Statistic_proto_goTypes,
		DependencyIndexes: file_Statistic_proto_depIdxs,
		EnumInfos:         file_Statistic_proto_enumTypes,
		MessageInfos:      file_Statistic_proto_msgTypes,
	}.Build()
	File_Statistic_proto = out.File
	file_Statistic_proto_rawDesc = nil
	file_Statistic_proto_goTypes = nil
	file_Statistic_proto_depIdxs = nil
}
